jet/FsCodec

- tests/Jet.JsonNet.Converters.Tests/PicklerTests.fs
A number of codebases register a global Guid rendering customization.
This PR adds such a converter as an acceptance test, with a comment explaining the rationale for not including it as a top level converter within the package itself.
> Add GuidConverter example

- Directory.Build.props
- Jet.JsonNet.Converters.sln
- src/Jet.JsonNet.Converters/Pickler.fs
- src/Jet.JsonNet.Converters/TypeSafeEnumConverter.fs
- src/Jet.JsonNet.Converters/UnionConverter.fs
- tests/Jet.JsonNet.Converters.Tests/UnionConverterTests.fs
A `TypeSafeEnum` when used as a tupled field is not validated and simply yields a `null` (and subsequent `NullReferenceException`s).
This fix addresses that by triggering an exception on conversion.
Note: this is debatable - my reasoning for making this a default behavior is that a converters can be made to cope with this signalling by having a specific handing for a `JToken.Null` input, and that the scope is limited to tupled Union cases using the `UnionConverter`
A follow-up PR will allow one to opt-in to handing this missing field case by wrapping the value in an `Option`
> Apply converters to tupled fields in UnionConverter to missing values fixes #1

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec/FsCodec.fs
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
This PR changes a tentative overload of `FsCodec.NewtonsoftJson.Codec.Create` which addresses a specific case cited by @rajivhost with a more general mechanism in line with the needs discussed in the context of @ameier's https://github.com/ameier38/equinox-tutorial
> NewtonsoftJson.Codec: Provide up/down conversion hooks and metadata access

- CHANGELOG.md
- src/FsCodec/FsCodec.fs
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
Cleanup, see #18. Will have small knock-on impacts in tests in Propulsion and Equinox, but so be it
> EventData, IndexedEventData consistency

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec/FsCodec.fs
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
See #18 
- `IEvent` can cause very time-consuming confusion due to the fact that `FSharp.Control.IEvent` is implicity in scope in F# code by default (ask me how I know)
- `IIndexedEvent` never made me happy
Improvements on either name are welcome!
CC @rajivhost intending to feed usage of this into Equinox and Propulsion soon, assuming no objections
> Rename IEvent, IIndexedEvent to IEventData, ITimelineEvent

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec/Codec.fs
- src/FsCodec/FsCodec.fs
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
While the current codec overloads allow one to supply a `down` function which can add contextual information to enrich an event, the codec needs to be generated freshly each time, or else it needs to grab values from some global context out of band.
This PR adds:
- well known `CorrelationId` and `CausationId` members on all Event Data interfaces
- `IUnionEncode.Encode` now admits a `'Context option` argument, which is made available to the `down` function in order to be able to generate same
Closes #21
> Provide support for derivation of CorrelationId / CausationId

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec/Codec.fs
Restores function signatures that were present in `1.0.0-rc2` which were removed in `1.0.0`
Provides a clearer `FsCodec.NewtosoftJson.Codec.Create` overload with a mapCausation function to facilitate cleaner metadata management
Provides a FsCodec.Codec overload with a similar signature
cc @rajivhost
> Add mapCausation overload, restore rc2 Codec overloads

- CHANGELOG.md
- README.md
- src/FsCodec.NewtonsoftJson/BoxCodec.fs
- src/FsCodec.NewtonsoftJson/FsCodec.NewtonsoftJson.fsproj
`FsCodec.Box.Codec` is a drop-in-equivalent for `FsCodec.NewtonsoftJson.Codec` with equivalent `.Create` overloads which encode as `ITimelineEvent<obj>` (as opposed to `ITimelineEvent<byte[]>`.
This is useful when storing events in a `MemoryStore` as it allows one to take the perf cost and ancillary yak shaving induced by round-tripping arbitrary event payloads out of the picture when writing property based tests.
NOTE this does not imply one should avoid testing this aspect; the opposite in fact -- one should apply the [Test Pyramid principles](https://martinfowler.com/articles/practical-test-pyramid.html):
- have a focused series of tests which validate that the various data represented in the event bodies are round-trippable a) in the chosen encoding format (i.e. UTF8 json) b) with the …
> Add BoxCodec

- CHANGELOG.md
- src/FsCodec/Codec.fs
As part of generalizing [Equnox's `MemoryStore`](https://github.com/jet/equinox/blob/master/src/Equinox.MemoryStore/MemoryStore.fs) to envelope the data as an `ITimelineEvent`, it makes sense to remove assumptions that UTF8 byte arrays should be the only encoding exposed.
> Generalize Codec to admit 'Format

- CHANGELOG.md
- README.md
- src/FsCodec/FsCodec.fsproj
- src/FsCodec/StreamName.fs
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
HT @thednaz who wouldn't let up!
> Add FsCodec.StreamName

- CHANGELOG.md
- README.md
- src/FsCodec/FsCodec.fs
- Should this be called `Tag` or `Properties` instead?
- Should this also go on `IEventData`?
- 🤔 Does `context` overlap with the `context` on the encoding side ?
- 🤔 should the generic `TryDecode` function require a `'Context option` and then box that into the `IEventData`?
> Add ITimelineEvent.Context

- CHANGELOG.md
- src/FsCodec/Codec.fs
The `'Format` type argument on `Codec.Create` methods was constrained to be nullable because the `data` and `metadata` fields are both set to be of type `'Format`, and `metadata` is set to `null` when it isn't explicitly provided by the `encode` delegate. This necessitated the null constraint. 
This PR makes it so that instead of setting the metadata value to `null`, it will instead be set to `default`. Accordingly, it also removes the null constraint from the `'Format` type argument.
> Remove null constraint from Format type arg

- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/JsonRecordConverter.fs
- src/FsCodec.SystemTextJson/Options.fs
- src/FsCodec.SystemTextJson/Pickler.fs
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/PicklerTests.fs
- tests/FsCodec.SystemTextJson.Tests/UmxInteropTests.fs
Port of original NewtonsoftJson impl by @eiriktsarpalis to work equivalently with `System.Text.Json` (separated for now for review purposes, part of #38)
> Port JsonIsomorphism from Newtonsoft variant

- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/JsonOptionConverter.fs
- src/FsCodec.SystemTextJson/TypeSafeEnumConverter.fs
- src/FsCodec.SystemTextJson/UnionConverter.fs
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/TypeSafeEnumConverterTests.fs
> Port TypeSafeEnum and Converter to System.Text.Json

- src/FsCodec.SystemTextJson/Options.fs
- tests/FsCodec.SystemTextJson.Tests/SerdesTests.fs
Alter the default `Options.Create()` behavior to [inhibit `System.Text.Json`s default over-escaping behavior](https://github.com/dotnet/runtime/issues/28567#issuecomment-53581752) when using `Options.Create()` and/or things that are transitively dependent on it, i.e., `Serdes`
closes #44
> Default to not over-escaping in SystemTextJson re #44

- README.md
- tests/FsCodec.SystemTextJson.Tests/CodecTests.fs
`Some null` renders as `null` atm; as evidenced by the diffs, removing that wart makes for less special cases in tests re #38
> Remove Some null handling wart

- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec.SystemTextJson/Codec.fs
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/Interop.fs
- tests/FsCodec.NewtonsoftJson.Tests/FsCodec.NewtonsoftJson.Tests.fsproj
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
- tests/FsCodec.SystemTextJson.Tests/CodecTests.fs
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/InteropTests.fs
In order to enable stores that demand `JsonElement` payloads to interop with FsCodec.NewtonsoftJson codecs
In order to enable stores that demand `byte[]` payloads to interop with FsCodecSystemTextJson codecs
Provide shims that adapt IEventCodecs of one shape to the other
re #38
> STJ: Add ToByteArrayCodec/ToJsonElementCodec shims

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/UnionConverter.fs
- tests/FsCodec.NewtonsoftJson.Tests/UnionConverterTests.fs
Nested unions don't roundtrip; this PR addresses that by removing the inlining of nested objects when a converter is in play
> UnionConverter: Handle Nested Unions

- README.md
- src/FsCodec/StreamName.fs
- tests/FsCodec.Tests/StreamNameTests.fs
This PR makes it clearer that `Identifier`s in `StreamName`s may contain hyphens.
Side note: the FsCodec readme mentions `$ec`, but I'm not seeing anything about that on ESDB's website or in their code. Is it perhaps out of date? I admittedly have not searched very hard.
> Hyphens in `StreamName` identifiers

- CHANGELOG.md
- README.md
- src/FsCodec.NewtonsoftJson/Serdes.fs
- src/FsCodec.SystemTextJson/Serdes.fs
Provide relatively easily-accessible API and guidance re integration with ASP.NET Core
> Add Serdes.DefaultOptions/Settings

- README.md
- tests/FsCodec.NewtonsoftJson.Tests/PicklerTests.fs
> Document+test coverage for upconversion of new object fields

- CHANGELOG.md
- src/FsCodec.SystemTextJson/UnionOrTypeSafeEnumConverterFactory.fs
- tests/FsCodec.NewtonsoftJson.Tests/SomeNullHandlingTests.fs
- tests/FsCodec.SystemTextJson.Tests/AutoUnionTests.fs
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/SerdesTests.fs
Fix for SystemTextJson 2.3.0 encoding e.g. `string option` as `{"case": "Some","Value":"X"}` rather than `"X"`
> Stop UnionOrTypeSafeEnumConverterFactory handling option/list

- src/FsCodec/StreamName.fs
It was messing up github rendering syntax highlighting of everything after it.
https://github.com/jet/FsCodec/blob/6e867e9815e965f6f4642bfa646e4ab6aa9c6caa/src/FsCodec/StreamName.fs#L40-L47
> Fix stray backtick in comment

- CHANGELOG.md
- Directory.Build.props
- README.md
- azure-pipelines.yml
- global.json
- src/FsCodec.Box/FsCodec.Box.fsproj
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec.NewtonsoftJson/FsCodec.NewtonsoftJson.fsproj
- src/FsCodec.NewtonsoftJson/Options.fs
- src/FsCodec.NewtonsoftJson/Serdes.fs
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/Serdes.fs
- src/FsCodec/FsCodec.fsproj
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
- tests/FsCodec.NewtonsoftJson.Tests/FsCodec.NewtonsoftJson.Tests.fsproj
- tests/FsCodec.NewtonsoftJson.Tests/PicklerTests.fs
- tests/FsCodec.NewtonsoftJson.Tests/SomeNullHandlingTests.fs
- tests/FsCodec.NewtonsoftJson.Tests/UnionConverterTests.fs
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/InteropTests.fs
- tests/FsCodec.Tests/FsCodec.Tests.fsproj
Main material change is to rename `NewtonsoftJson.Settings` to `Options` to align naming for ease of migrating between serializers.
Removing cruft as there are breaking changes on the way
resolves #60
> Remove net461; switch to net6.0

- CHANGELOG.md
- README.md
- src/FsCodec.Box/Codec.fs
- src/FsCodec.Box/CoreCodec.fs
- src/FsCodec.Box/FsCodec.Box.fsproj
- src/FsCodec.Box/Interop.fs
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec.NewtonsoftJson/FsCodec.NewtonsoftJson.fsproj
- src/FsCodec.SystemTextJson/Codec.fs
- src/FsCodec.SystemTextJson/CoreCodec.fs
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/Interop.fs
- src/FsCodec/FsCodec.fs
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
- tests/FsCodec.SystemTextJson.Tests/CodecTests.fs
- tests/FsCodec.SystemTextJson.Tests/InteropTests.fs
In Equinox V4, stores now accept/provide events in two primary formats (previously everything was `byte[]`):
- `ReadOnlyMemory<byte>`: Replaces `byte[]` as the default event body type, in order to facilitate pooling etc (EventStoreDB uses it directly, Equinox.DynamoStore maps internally to what the AWS SDK demands at present (`MemoryStream`))
- `JsonElement`: `Equinox.CosmosStore` now natively uses `System.Text.Json` so event bodies can be emitted cleanly and directly using that format
The key change is that `SystemTextJson` now has two `static type` roots;
- `CodecJsonElement`, which is for use with `Equinox.CosmosStore` V4 and later
- `Codec` (which previously produced a `JsonElement` codec) that needed to be adapted for use with `Equinox.CosmosStore` is now equivalent in signature to …
> Codec: Add/default to ReadOnlyMemory format instead of byte[]

- CHANGELOG.md
- README.md
- src/FsCodec.Box/Interop.fs
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec.NewtonsoftJson/VerbatimUtf8Converter.fs
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/Interop.fs
- src/FsCodec/FsCodec.fs
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
- tests/FsCodec.SystemTextJson.Tests/InteropTests.fs
These mapping helpers are useful in various contexts within Equinox and Propulsion, but likely also for people juggling their own arbitrary event envelopes.
> Expose Map on TimelineEvent/EventData/EventCodec

- CHANGELOG.md
- README.md
- src/FsCodec.Box/Codec.fs
- src/FsCodec.Box/CoreCodec.fs
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec.SystemTextJson/Codec.fs
- src/FsCodec.SystemTextJson/CodecJsonElement.fs
- src/FsCodec/Codec.fs
- src/FsCodec/FsCodec.fs
- src/FsCodec/StreamName.fs
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
- tests/FsCodec.NewtonsoftJson.Tests/VerbatimUtf8ConverterTests.fs
- tests/FsCodec.SystemTextJson.Tests/CodecTests.fs
- tests/FsCodec.SystemTextJson.Tests/Examples.fsx
- tests/FsCodec.SystemTextJson.Tests/InteropTests.fs
- tests/FsCodec.Tests/StreamNameTests.fs
- tests/FsCodec.Tests/TryDeflateTests.fs
- Convert all Tuple/Option types to the `struct` versions - can be a touch ugly in usage, but hopefully future F# versions make it less so; also applied to active patterns
- Major other change is to switch `'context` from an `option` that's stubbed as an `obj` to be a `unit` when not relevant
- Add `TimelineEvent.Size` field to allow gathering stats without inspecting the `Data`
Including some minor other profiling-driven optimizations in StreamName
> Struct Tuples/Options

- CHANGELOG.md
- README.md
- src/FsCodec/StreamName.fs
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
- tests/FsCodec.SystemTextJson.Tests/Examples.fsx
Provides for cleaner pattern matching when filtering by category without having to drop the streamId portion
> Add StreamName.[Cc]ategory

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/OptionConverter.fs
- src/FsCodec.NewtonsoftJson/Options.fs
- src/FsCodec.NewtonsoftJson/TypeSafeEnumConverter.fs
- src/FsCodec.NewtonsoftJson/UnionConverter.fs
- src/FsCodec.SystemTextJson/Options.fs
- src/FsCodec.SystemTextJson/TypeSafeEnumConverter.fs
- src/FsCodec.SystemTextJson/UnionConverter.fs
While we still have separate impls per serializer, this aligns the signatures
> Newtonsoft: Sync TypeSafeEnum signatures

- CHANGELOG.md
- README.md
- src/FsCodec.Box/Codec.fs
- src/FsCodec.Box/CoreCodec.fs
- src/FsCodec.NewtonsoftJson/Codec.fs
- src/FsCodec.NewtonsoftJson/FsCodec.NewtonsoftJson.fsproj
- src/FsCodec.NewtonsoftJson/Options.fs
- src/FsCodec.NewtonsoftJson/Serdes.fs
- src/FsCodec.NewtonsoftJson/VerbatimUtf8Converter.fs
- src/FsCodec.SystemTextJson/Codec.fs
- src/FsCodec.SystemTextJson/CodecJsonElement.fs
- src/FsCodec.SystemTextJson/Options.fs
- src/FsCodec.SystemTextJson/Serdes.fs
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
- tests/FsCodec.NewtonsoftJson.Tests/PicklerTests.fs
- tests/FsCodec.NewtonsoftJson.Tests/SomeNullHandlingTests.fs
- tests/FsCodec.NewtonsoftJson.Tests/StreamTests.fs
- tests/FsCodec.NewtonsoftJson.Tests/UnionConverterTests.fs
- tests/FsCodec.SystemTextJson.Tests/AutoUnionTests.fs
- tests/FsCodec.SystemTextJson.Tests/CodecTests.fs
- tests/FsCodec.SystemTextJson.Tests/Examples.fsx
- tests/FsCodec.SystemTextJson.Tests/SerdesTests.fs
- tests/FsCodec.SystemTextJson.Tests/TypeSafeEnumConverterTests.fs
- tests/FsCodec.Tests/TryDeflateTests.fs
Also refactor, pushing the BytesEncoder logic out to 'add' NewtonsoftJson.Serdes.SerializeToUtf8 as advertised in #94
> Add Serdes.Default

- CHANGELOG.md
- README.md
- src/FsCodec.NewtonsoftJson/UnionConverter.fs
- src/FsCodec/FsCodec.fsproj
- src/FsCodec/StreamId.fs
- src/FsCodec/StreamName.fs
- tests/FsCodec.NewtonsoftJson.Tests/Fixtures.fs
- tests/FsCodec.SystemTextJson.Tests/Examples.fsx
- tests/FsCodec.Tests/StreamNameTests.fs
Heavily inspired by #99 and related out of band discussions with @nordfjord 
Intended to replace Equinox.StreamId, Equinox.Core.StreamId and Equinox.Core.StreamName
> feat!: StreamId

- CHANGELOG.md
- README.md
- src/FsCodec.NewtonsoftJson/OptionConverter.fs
- src/FsCodec.NewtonsoftJson/Pickler.fs
- src/FsCodec.NewtonsoftJson/TypeSafeEnumConverter.fs
- src/FsCodec.NewtonsoftJson/UnionConverter.fs
- src/FsCodec.SystemTextJson/Pickler.fs
- src/FsCodec.SystemTextJson/TypeSafeEnumConverter.fs
- src/FsCodec.SystemTextJson/UnionConverter.fs
- src/FsCodec.SystemTextJson/UnionOrTypeSafeEnumConverterFactory.fs
- src/FsCodec/FsCodec.fsproj
- src/FsCodec/TypeSafeEnum.fs
- src/FsCodec/Union.fs
- tests/FsCodec.NewtonsoftJson.Tests/Examples.fsx
- tests/FsCodec.SystemTextJson.Tests/AutoUnionTests.fs
- tests/FsCodec.SystemTextJson.Tests/Examples.fsx
- tests/FsCodec.SystemTextJson.Tests/TypeSafeEnumConverterTests.fs
The `TypeSafeEnum` helper class initially lived in NewtonsoftJson as it was an internal impl detail of the converter
The STJ reimpl did some optimisation etc while following the same API
This comes to a head on the consumption side if you need to programmatically manipulate Union and/or TypeSafeEnum generically; abusing `FsCodec.SystemTextJson.TypeSafeEnum.toString` makes things very confusing.
> feat(TypeSafeEnum): Merged impls; exposed Union

- CHANGELOG.md
- src/FsCodec.Box/CoreCodec.fs
Though it arguably does not matter due to the Offset being included in the stored form, it's best for this to match the documentation (yes, despite it having been this way for some time)
> fix!: Change default Event timestamp to UtcNow

- CHANGELOG.md
- README.md
- src/FsCodec.NewtonsoftJson/FsCodec.NewtonsoftJson.fsproj
FsCodec is only a library, and the host application ultimately controls the specific JSON.NET version. As such, it can be argued that the minimum is not relevant.
However, we're about to roll to v3, so pulls in a version of a library [that's been flagged](https://www.nuget.org/packages/newtonsoft.json/11.0.2) is problematic as the default behavior for an app using the library via NuGet will be to take the minimum required
- Originally flagged (and intentionally avoided on the 'the host owns it' basis mentioned in the overview) in #89
> fix: Update min Newtonsoft dependency to 13.0.3

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/Options.fs
Change `Options.CreateDefault` (and `.Create`, and `.Default` etc) to avoid falling into JNK's epic trolling default trap in https://github.com/JamesNK/Newtonsoft.Json/issues/862
> fix!: Workaround for JamesNK/Newtonsoft.Json#862

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/Pickler.fs
- src/FsCodec.NewtonsoftJson/UnionConverter.fs
- src/FsCodec.SystemTextJson/Pickler.fs
- src/FsCodec.SystemTextJson/UnionOrTypeSafeEnumConverterFactory.fs
Removes two speculative 'features' that can be reaonably argued to be misfeatures on the basis that they were not documented, nor were they covered by tests:
1. `JsonPickler` no longer supports implicit application (via inclusion in the converters list) to parent types or interfaces
- (also affects `JsonIsomorphism`, which `inherit`s from it)
2. `SystemTextJson.Options`: `autoTypeSafeEnumToJsonString, union = autoUnionToJsonObject` are skipped if the type nominates a specific converter directly (used to also honor tags on base classes/interfaces)
In both cases, the workaround if this greediness was intentionally required, is to override the `CanConvert` member on the converter (or `UnionOrTypeSafeEnumConverterFactory`)
> fix(JsonPicker, JsonIsomorphism, UnionConverter)!: Reduce greediness

- CHANGELOG.md
- src/FsCodec.NewtonsoftJson/FsCodec.NewtonsoftJson.fsproj
- src/FsCodec.NewtonsoftJson/StringIdConverter.fs
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/StringIdConverter.fs
- src/FsCodec/FsCodec.fsproj
- src/FsCodec/StringId.fs
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/StringIdTests.fs
These have long lived in the Equinox Samples Folder
Adding them here as an undocumented feature to give `StringIdOrDictionaryKeyConverter` a home
> feat: Comparable, StringId, StringIdConverter

- CHANGELOG.md
FsCodec does not lean on the vulnerable method and hence this is not strictly required
Applications that use FsCodec.SystemTextJson will work correctly if v 8.0.4 of `System.Text.Json` is use in the context of the app.
> chore(SystemTextJson, deps): Target minimum non vulnerable ver: 8.0.4

- CHANGELOG.md
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- tests/FsCodec.NewtonsoftJson.Tests/FsCodec.NewtonsoftJson.Tests.fsproj
- tests/FsCodec.SystemTextJson.Tests/FsCodec.SystemTextJson.Tests.fsproj
- tests/FsCodec.Tests/FsCodec.Tests.fsproj
#122 upped the dep to 8.0.4, but dropping it back down as 6.0.10 is a healthy alternative - no CVEs, and the minimum required for the features in this package as per normal minimal policy
Eventually the dependency being upped to 8/10/12.x is inevitable, but no need to rush it
> chore(deps): Drop SystemTextJson minimum to 6.0.10

- CHANGELOG.md
- src/FsCodec.Box/Compression.fs
- src/FsCodec.Box/FsCodec.Box.fsproj
- src/FsCodec.SystemTextJson/FsCodec.SystemTextJson.fsproj
- src/FsCodec.SystemTextJson/Interop.fs
- src/FsCodec/FsCodec.fs
Passes additional context to the encoding function.
e.g. For `SystemTextJson.Encoding`, this enables the `shouldCompress` predicate to control compression based on the `EventType` etc
NOTE this is a half way house solution - eventually `IEventData` should take over ownership of `IsUnfold` and `Context` from `ITimelineEvent` to afford better control of encoding for DynamoStore and CosmosStore without indirect assumptions
> feat(EventData): Add MapBodies overload with context
